// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ApiConcessionaria.Models
{
    public partial class Carro
    {
        [Key]
        public int Id { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string Chassi { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Modelo { get; set; }
        public int? Ano { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Cor { get; set; }

    }
}